services:
  auth-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${AUTH_POSTGRES_USER} -d $${AUTH_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_postgres_data:
